name: Run Maven Test in restdemo

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build project
      run: mvn -f restdemo/pom.xml clean install

    - name: Run tests
      run: mvn -f restdemo/pom.xml test

      # Optional: specify additional arguments to mvn test command
      # with:
      #   args: -Dtest=my.package.MyTestClass#myTestMethod

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: restdemo/target/surefire-reports/
