name: Run Maven Test in restdemo

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: '11'

    - name: Build project
      run: mvn -f restdemo/pom.xml clean install

    - name: Run tests
      run: mvn -f restdemo/pom.xml test
