name: Run Maven Test in restdemo

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution : 'adopt'

    - name: Set up environment
      env:
        DB_URL: jdbc:mysql://localhost:3306/student_tracker
        DB_USERNAME: springstudent
        DB_PASSWORD: springstudent
      run: echo "Setting up environment variables"

    - name: Build project
      run: mvn -f restdemo/pom.xml clean install

    - name: Run tests
      run: mvn -f restdemo/pom.xml test
